/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-web:2.7.2")
    api("org.projectlombok:lombok:1.18.24")
    api("org.openjdk.jmh:jmh-core:1.33")
    api("org.openjdk.jmh:jmh-generator-annprocess:1.33")
    api("com.google.guava:guava:31.0.1-jre")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.7.2")
}

group = "org.roon"
version = "0.0.1-SNAPSHOT"
description = "JMHPractice"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
